Fix for failing 'focus.application.node' seting
Test failure:
Traceback (most recent call last):
File "/home/travis/build/roignac/dogtail/tests/gtkdemotest.py", line 15, in setUp
  self.pid = dogtail.utils.run('gtk3-demo')
File "/home/travis/build/roignac/dogtail/dogtail/utils.py", line 118, in run
  focus.application.node = child
File "/home/travis/build/roignac/dogtail/dogtail/procedural.py", line 57, in __setattr__
  self.__class__.__dict__[name] = value
TypeError: 'dictproxy' object does not support item assignment