Trap GErrors in findAllDescendants and retry if it occurs
This fixes crashes in findChildren if elements are being added/removed quickly:
GError: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" could not be processed as object /org/a11y/atspi/accessible/2310 does not exist